### ISSUE TITLE
Hello and Thank You First Off and Secondly...

### ISSUE THREAD

**Issue by silver2row** [printedgadgets/3D-Printed-Robot-Dog#1]
Hello,

I have been following you to find out more about this item. I appreciate you building this idea and publishing it. I contacted you many times in the forum posts on the Instructables site. I am silver2row on the Instructables site too.

Anyway, I am building this contraption. The Quadruped in question has changed a bit b/c of my board(s) of use. So, I am using a BeagleBone Black SBC and their ServoCape for the hardware and brains of the machine.

...

One query I have here is this idea:

```
How can I control two motors at the same time w/ the fixed, 3D Printed parts?
```

It seems that my source is a bit discouraging so far. I mean...I can control them but I am having a hard time finding how the exact connection mechanically will work w/ the two connections.

I have the source, which can be found here: https://github.com/silver2row/ServoCape .

I also made a notion of a start which credits you for the build at https://www.hackster.io/functt/servocape-beaglebone-black-and-pca9685-4d2d10 .

For now, I have the 180 degrees of freedom per servo, i.e. the DS3218 which is found online here: https://www.dsservo.com/en/d_file/DS3218%20datasheet.pdf .

So, my question is b/c of my lack of experience here. Just getting the servos to move via an online server or by the command line is not working for me for a particular reason.

```
Is there a particular angle of hardware applied to the servo to start w/ the scripts?
```

Seth

P.S. I am sorry if this is elongated and boring. I am just reaching out to see if you understand what it may be that I am coming across w/ the build so far.

Also...I am going to add a video of what I am discussing. Please excuse the slow talking from me and the bad background music. Anyway, I will post it soon.

**Comment by silver2row** [comment]
Hello Again Sir,

Seth here. Here is the video. It seems when I control the two servos at the same angle, this is where the mechanics come into play w/ friction and blocking of parts. Anyway, I can now control the two servos independently.

I will attempt this effort in a better way as time progresses but for now, here is the video of the two motors hitting angle 0, angle 90, and angle 135: https://vimeo.com/771436130

Seth

P.S. If this is not something to chat about, okay. I can back off.

**Comment by aaedmusa** [comment]
Hey Seth. So if I understand correctly you are trying to get this set up with a different board? Does this board use Arduino code? I’m not familiar with the board itself so I may not be of much help.

**Comment by silver2row** [comment]
Hello,

No...it uses gnu glibc and other forms of software languages. Not arduino specific. Anyway, I thought you may like this since you are an excellent artist/engineer of CAD and programming: https://efests.asme.org/competitions/asme-extended-reality-challenge .

Seth

P.S. Anyway, I am doing better w/ the programing aspects to the board. So, no issue there any longer. Sorry to bother you about my tasks at hand. I was just reaching out.
